### ISSUE TITLE
Issue requiring serverless-plugin-chrome

### ISSUE THREAD

**Issue by benjaminwood** [adieuadieu/serverless-chrome#34]
Thanks @adieuadieu for your work on serverless-chrome! I'm new to serverless and I'm having an issue that I'm not sure how to resolve. I'd like to use `serverless-plugin-chrome` along with the [`serverless-offline`](https://github.com/dherault/serverless-offline) plugin.

The plugins entry in my serverless.yml looks like this:

```
plugins:
  - serverless-plugin-chrome
  - serverless-offline
```

I've tried reversing the order, but that seems to have no effect. Can you offer any advise? Let me know if I can provide any other information that'd be helpful to you. Thanks!

I've triple-checked that I have installed `serverless-plugin-chrome` via `yarn add --dev serverless-plugin-chrome`.

### Version info
>     OS:                     darwin
>     Node Version:           8.1.3
>     Serverless Version:     1.17.0
>     serverless-plugin-chrome Version: 1.0.0-7
>     serverless-offline Version: 3.15.0

### Stack trace:
```
➜  serverless-exports SLS_DEBUG=* sls offline start --port 3001

  Error --------------------------------------------------

  Cannot find module 'serverless-plugin-chrome'

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: Cannot find module 'serverless-plugin-chrome'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at plugins.forEach (/Users/Ben/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:65:22)
    at Array.forEach (native)
    at PluginManager.loadPlugins (/Users/Ben/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:64:13)
    at PluginManager.loadServicePlugins (/Users/Ben/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:91:10)
    at PluginManager.loadAllPlugins (/Users/Ben/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:60:10)
    at service.load.then (/Users/Ben/.config/yarn/global/node_modules/serverless/lib/Serverless.js:72:28)
    at <anonymous>
From previous event:
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at __dirname (/Users/Ben/.config/yarn/global/node_modules/serverless/bin/serverless:20:28)
    at Object.<anonymous> (/Users/Ben/.config/yarn/global/node_modules/serverless/bin/serverless:36:4)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

**Comment by adieuadieu** [comment]
Hi @benjaminwood,

Hm.. That's a weird/unexpected error. I haven't had a chance to thoroughly test the plugin together with `serverless-offline`, so can't say that it _should_ work. I wouldn't entirely be surprised if it didn't. The serverless-chrome plugin currently only somewhat [lazily hooks](https://github.com/adieuadieu/serverless-chrome/blob/develop/packages/serverless-plugin/src/index.js#L40) into the `serverless-offline` hooks. However, you shouldn't be getting the error you're seeing.

Would you be able to share your code? Specifically of interest is your `package.json` and the handler code (you can omit any business logic.)

**Comment by benjaminwood** [comment]
Hey @adieuadieu thanks for the quick response! I just recreated the problem in a simpler scenario.

It appears that I either have an issue with my environment (likely?) or there is a problem with the package. I just went through the following:

- `mkdir test`
- `cd test`
- `yarn add --dev serverless-plugin-chrome`
- `node -e "require('serverless-plugin-chrome')"`

I can install and require other packages this way, but not `serverless-plugin-chrome`. Strange huh?

**Comment by adieuadieu** [comment]
Ah. 

I just published a new version to NPM. Could upgrade `serverless-plugin-chrome` and try again?

Also, just to clarify: You don't need to include `serverless-plugin-chrome` directly into your code. Adding it to `serverless.yml`'s `plugins` section should be all you need to do (besides yarn installing it.)

**Comment by benjaminwood** [comment]
Funny! I was just poking around in package.json and noticed `dist/index.cjs.js`.

I see the change you made, and I suspect this is the problem I'm running into. However, there is no `dist` directory in the new version. Perhaps you forgot to include it in the new package/version?

Regarding requiring `serverless-plugin-chrome`, I was only requiring it manually to see if I could recreate the issue outside of serverless, serverless-offline, etc.

**Comment by adieuadieu** [comment]
Hm.. Looks like I ran into [this](https://github.com/npm/npm/issues/15454) issue with NPM. Just published a _new_ new version.

**Comment by benjaminwood** [comment]
It works!!!

**Comment by benjaminwood** [comment]
Thanks for your help and thanks again for your work on this project. Are you on gitter chat or anything similar?

**Comment by adieuadieu** [comment]
Great! Glad to hear it works for you now. I'm occasionally on Gitter, but not very active.

**Comment by benjaminwood** [comment]
👍 I'll close this out now.

Ps. I've got a PR coming your way for another bugfix. 😄
